apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Energy PostgreSQL
    uid: energy-postgres
    type: postgres
    url: postgres:5432
    user: energy
    secureJsonData:
      password: energy
    jsonData:
      database: energy
      sslmode: disable
      postgresVersion: 1700

